# BUILD #

[build]
	publish = "dist/static"
	command = "npm run jam" # we don't wanna puppeteer process vulgares-guard -> no --scanRoute



# SEO #

[[plugins]]
  package = "netlify-plugin-submit-sitemap" # <-> ("@netlify/plugin-sitemap" from Netlify UI installed too)

	[plugins.inputs]
	sitemapPath = "/sitemap.xml"
	providers = ["google"]   # (default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	# baseUrl = "https://example.com"   # (optional, default = main URL set in Netlify)

	

# PERFORMANCE #

 [[plugins]]
 	package = "netlify-plugin-minify-html"
 	
 	[plugins.inputs]
 	  contexts = ['production']
 	
 	[plugins.inputs.minifierOptions]
 	  caseSensitive = true
 	  removeComments = true
 		collapseWhitespace = true
 		preserveLineBreaks = false # (def)
 		html5 = true # (def)


# "netlify-plugin-inline-critical-css" # -> (Plugin with Bugs. Don't use it!)
# Netlify UI > Build > PotProcessing > Assets Optimization (incompatible with Scully. Don't use'm!)



# SECURITY #

# "netlify-plugin-is-website-vulnerable" # -> from Netlify UI (no toml config needed yet)
