# BUILD #

[build]
	publish = "dist/static"
	command = "npm run jam:sc"



# SEO #

[[plugins]]
  package = "netlify/plugin-sitemap" # -> we need config (automaticaly report sitemap to google)

	[plugins.inputs]
	# baseUrl = "https://example.com" # (default = main URL set in Netlify)
	sitemapPath = "/sitemap.xml"

	# Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = ["google"]



# PERFORMANCE #

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = ['production']

  [plugins.inputs.minifierOptions]
    caseSensitive = true
    removeComments = true
		collapseWhitespace = true
		preserveLineBreaks = false # (def)
		html5 = true # (def)


# "netlify-plugin-inline-critical-css" -> (Plugin with Bugs. don't use it)



# SECURITY #

# "netlify-plugin-is-website-vulnerable" -> from Netlify UI (no toml config needed yet)